[package]
name = "cosmwasm-vm"
version = "0.12.1"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "VM bindings to run cosmwams contracts"
repository = "https://github.com/CosmWasm/cosmwasm/tree/master/packages/vm"
license = "Apache-2.0"

[badges]
circle-ci = { repository = "CosmWasm/cosmwasm", branch = "master" }
maintenance = { status = "actively-developed" }

[features]
default = ["staking"]
# The backtraces fature is unused for now, i.e. it does nothing.
backtraces = []
# iterator allows us to iterate over all DB items in a given range
# this must be enabled to support cosmwasm contracts compiled with the 'iterator' feature
# optional as some merkle stores (like tries) don't support this
# given Ethereum 1.0, 2.0, Substrate, and other major projects use Tries
# we keep this optional, to allow possible future integration (or different Cosmos Backends)
iterator = ["cosmwasm-std/iterator"]
staking = ["cosmwasm-std/staking"]
metering = []
# Use cranelift backend instead of singlepass. This is required for development on Windows.
cranelift = ["wasmer/cranelift"]

[lib]
# See https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false

[dependencies]
clru = "0.2.0"
# Uses the path when built locally; uses the given version from crates.io when published
cosmwasm-std = { path = "../std", version = "0.12.1" }
hex = "0.4"
memmap = "0.7"
parity-wasm = "0.42"
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive", "alloc"] }
serde_json = "1.0"
sha2 = "0.9.1"
thiserror = "1.0"
wasmer = { git = "https://github.com/wasmerio/wasmer", rev = "e1c92737", default-features = false, features = ["jit", "singlepass"] }
wasmer-engine = { git = "https://github.com/wasmerio/wasmer", rev = "e1c92737" }

# Wasmer local (used for quick local debugging or patching)
# wasmer = { path = "../../../wasmer/lib/api", default-features = false, features = ["jit", "singlepass"] }
# wasmer-engine = { path = "../../../wasmer/lib/engine" }

[dev-dependencies]
criterion = "0.3"
tempfile = "3.1.0"
wat = "1.0"

[[bench]]
name = "main"
harness = false
