[package]
name = "cosmwasm-vm"
version = "0.10.1"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "VM bindings to run cosmwams contracts"
repository = "https://github.com/CosmWasm/cosmwasm/tree/master/packages/vm"
license = "Apache-2.0"

[badges]
circle-ci = { repository = "CosmWasm/cosmwasm", branch = "master" }
maintenance = { status = "actively-developed" }

[features]
default = ["default-singlepass", "staking"]
# multiple backends may be activated here (available through eg. backends::cranelift::*)
cranelift = ["wasmer-compiler-cranelift"]
singlepass = ["wasmer-compiler-singlepass"]
# default selects which *one* is re-exported in backends/mod.rs (available through eg backends::*)
default-cranelift = ["wasmer-compiler-cranelift"]
default-singlepass = ["wasmer-compiler-singlepass"]
# enable this for better error reporting
backtraces = ["snafu/backtraces"]
# iterator allows us to iterate over all DB items in a given range
# this must be enabled to support cosmwasm contracts compiled with the 'iterator' feature
# optional as some merkle stores (like tries) don't support this
# given Ethereum 1.0, 2.0, Substrate, and other major projects use Tries
# we keep this optional, to allow possible future integration (or different Cosmos Backends)
iterator = ["cosmwasm-std/iterator"]
staking = ["cosmwasm-std/staking"]

[dependencies]
# Uses the path when built locally; uses the given version from crates.io when published
cosmwasm-std = { path = "../std", version = "0.10.1" }
serde_json = "1.0"
wasmer = { path = "../../../wasmer-reborn/lib/api" }
wasmer-compiler-cranelift = { path = "../../../wasmer-reborn/lib/compiler-cranelift", optional = true }
wasmer-compiler-singlepass = { path = "../../../wasmer-reborn/lib/compiler-singlepass", optional = true }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive", "alloc"] }
snafu = { version = "0.6.3" }
sha2 = "0.9.1"
hex = "0.4"
memmap = "0.7"
parity-wasm = "0.41"

[dev-dependencies]
tempfile = "3.1.0"
wabt = "0.9.1"
