[package]
name = "cw-check-contract"
version = "1.0.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2021"
description = "VM bindings to run verify cosmos contracts."
repository = "https://github.com/CosmWasm/cosmwasm/tree/main/packages/cw-check-contract"
license = "Apache-2.0"

[dependencies]
cosmwasm-vm = { path = "../vm" }
cosmwasm-std = { path = "../std" }
clap = "2.33.3"
