[package]
name = "cosmwasm-profiler"
version = "0.16.0-rc5"
authors = ["Tomasz Kurcz <uint@lavabit.com>"]
edition = "2018"
description = "A profiling utility for compiled Cosmwasm smart contracts"
repository = "https://github.com/CosmWasm/cosmwasm/tree/main/packages/profiler"
license = "Apache-2.0"
readme = "README.md"

[dependencies]
