[package]
name = "cosmwasm-schema"
version = "1.1.6"
authors = ["Simon Warta <webmaster128@users.noreply.github.com>", "Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2021"
description = "A dev-dependency for CosmWasm contracts to generate JSON Schema files."
repository = "https://github.com/CosmWasm/cosmwasm/tree/main/packages/schema"
license = "Apache-2.0"

[dependencies]
cosmwasm-schema-derive = { version = "=1.1.6", path = "../schema-derive" }
schemars = "0.8.3"
serde = "1.0"
serde_json = "1.0.40"
thiserror = "1.0.13"

[dev-dependencies]
anyhow = "1.0.57"
semver = "1"
tempfile = "3"
