[package]
name = "cosmwasm-schema"
version = "1.0.0-rc.0"
authors = ["Simon Warta <webmaster128@users.noreply.github.com>", "Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2021"
description = "A dev-dependency for CosmWasm contracts to generate JSON Schema files."
repository = "https://github.com/CosmWasm/cosmwasm/tree/main/packages/schema"
license = "Apache-2.0"

[dependencies]
schemars = "0.8.1"
serde_json = "1.0"
