version: 2
workflows:
  version: 2
  test:
    jobs:
      - std
      - singlepass_vm
      - cranelift_vm
      - hackatom
      - hackatom_in_singlepass_vm
      - fmt
      - clippy

jobs:
  std:
    docker:
      - image: rust:1.41.1
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version; rustup target list --installed
      - restore_cache:
          keys:
            - cargocache-v2-std-rust:1.41.1-{{ checksum "Cargo.lock" }}
      - run:
          name: Add wasm32 target
          command: rustup target add wasm32-unknown-unknown && rustup target list --installed
      - run:
          name: Build library for native target
          working_directory: ~/project/packages/std
          command: cargo build --locked
      - run:
          name: Build library for wasm target
          working_directory: ~/project/packages/std
          command: cargo wasm --locked
      - run:
          name: Run unit tests
          working_directory: ~/project/packages/std
          command: cargo test --locked
      - run:
          name: Build library for native target (with iterator support)
          working_directory: ~/project/packages/std
          command: cargo build --locked --features iterator
      - run:
          name: Build library for wasm target (with iterator support)
          working_directory: ~/project/packages/std
          command: cargo wasm --locked  --features iterator
      - run:
          name: Run unit tests (with iterator support)
          working_directory: ~/project/packages/std
          command: cargo test --locked  --features iterator
      - run:
          name: Build and run schema generator
          working_directory: ~/project/packages/std
          command: cargo schema --locked
      - run:
          name: Ensure schemas are up-to-date
          command: |
            CHANGES_IN_REPO=$(git status --porcelain)
            if [[ -n "$CHANGES_IN_REPO" ]]; then
              echo "Repository is dirty. Showing 'git status' and 'git --no-pager diff' for debugging now:"
              git status && git --no-pager diff
              exit 1
            fi
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: cargocache-v2-std-rust:1.41.1-{{ checksum "Cargo.lock" }}

  singlepass_vm:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - run:
          name: Install CMake (required for compiling wabt-sys, a dev dependency of the VM)
          command: 'apt-get update && apt-get install -y cmake'
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version; rustup target list --installed
      - restore_cache:
          keys:
            - cargocache-v2-singlepass-rust:nightly-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets (including workspaces)
          working_directory: ~/project/packages/vm
          command: cargo build --locked
      - run:
          name: Run all tests (including workspaces)
          working_directory: ~/project/packages/vm
          command: cargo test --locked
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: cargocache-v2-singlepass-rust:nightly-{{ checksum "Cargo.lock" }}

  cranelift_vm:
    docker:
      - image: rust:1.41.1
    steps:
      - checkout
      - run:
          name: Install CMake (required for compiling wabt-sys, a dev dependency of the VM)
          command: 'apt-get update && apt-get install -y cmake'
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version; rustup target list --installed
      - restore_cache:
          keys:
            - cargocache-v2-cranelift-rust:1.41.1-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets (including workspaces)
          working_directory: ~/project/packages/vm
          command: cargo build --locked --no-default-features --features default-cranelift
      - run:
          name: Run all tests (including workspaces)
          working_directory: ~/project/packages/vm
          command: cargo test --locked --no-default-features --features default-cranelift
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: cargocache-v2-cranelift-rust:1.41.1-{{ checksum "Cargo.lock" }}

  hackatom:
    docker:
      - image: rust:1.41.1
    working_directory: ~/cosmwasm/contracts/hackatom
    steps:
      - checkout:
          path: ~/cosmwasm
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - restore_cache:
          keys:
            - cargocache-v2-hackatom-rust:1.41.1-{{ checksum "Cargo.lock" }}
      - run:
          name: Add wasm32 target
          command: rustup target add wasm32-unknown-unknown && rustup target list --installed
      - run:
          name: Build wasm binary
          command: cargo wasm --locked
      - run:
          name: Unit tests
          env: RUST_BACKTRACE=1
          command: cargo unit-test --locked
      - run:
          name: Integration tests
          command: cargo integration-test --locked
      - run:
          name: Build and run schema generator
          command: cargo schema --locked
      - run:
          name: Ensure schemas are up-to-date
          command: |
            CHANGES_IN_REPO=$(git status --porcelain)
            if [[ -n "$CHANGES_IN_REPO" ]]; then
              echo "Repository is dirty. Showing 'git status' and 'git --no-pager diff' for debugging now:"
              git status && git --no-pager diff
              exit 1
            fi
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
            - target/wasm32-unknown-unknown/release/.fingerprint
            - target/wasm32-unknown-unknown/release/build
            - target/wasm32-unknown-unknown/release/deps
          key: cargocache-v2-hackatom-rust:1.41.1-{{ checksum "Cargo.lock" }}

  # In this job we use singlepass as the VM to execute integration tests. This requires Rust nightly.
  # Avoid duplicating generic checks like unit tests or schema generation – they belong in the generic hackatom job.
  hackatom_in_singlepass_vm:
    docker:
      - image: rustlang/rust:nightly
    working_directory: ~/cosmwasm/contracts/hackatom
    steps:
      - checkout:
          path: ~/cosmwasm
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - restore_cache:
          keys:
            - cargocache-v2-hackatom_in_singlepass_vm-rust:nightly-{{ checksum "Cargo.lock" }}
      - run:
          name: Add wasm32 target
          command: rustup target add wasm32-unknown-unknown && rustup target list --installed
      - run:
          name: Build wasm binary
          command: cargo wasm --locked
      - run:
          name: Integration tests
          command: cargo integration-test --no-default-features --features singlepass --locked
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
            - target/wasm32-unknown-unknown/release/.fingerprint
            - target/wasm32-unknown-unknown/release/build
            - target/wasm32-unknown-unknown/release/deps
          key: cargocache-v2-hackatom_in_singlepass_vm-rust:nightly-{{ checksum "Cargo.lock" }}

  fmt:
    docker:
      - image: rust:1.41.1
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version; rustup target list --installed
      - restore_cache:
          keys:
            - cargocache-v2-fmt-rust:1.41.1-{{ checksum "Cargo.lock" }}
      - run:
          name: Add rustfmt component
          command: rustup component add rustfmt
      - run:
          name: Cargo format
          command: cargo fmt
      - run:
          name: Cargo format hackatom
          command: cd contracts/hackatom && cargo fmt
      - run:
          name: Ensure checked-in source code is properly formatted
          command: |
            CHANGES_IN_REPO=$(git status --porcelain)
            if [[ -n "$CHANGES_IN_REPO" ]]; then
              echo "Repository is dirty. Showing 'git status' for debugging now:"
              git status
              exit 1
            fi
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: cargocache-v2-fmt-rust:1.41.1-{{ checksum "Cargo.lock" }}

  clippy:
    docker:
      - image: rust:1.41.1
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version; rustup target list --installed
      - restore_cache:
          keys:
            - cargocache-v2-clippy-rust:1.41.1-{{ checksum "Cargo.lock" }}
      - run:
          name: Add clippy component
          command: rustup component add clippy
      - run:
          name: Clippy linting on std
          working_directory: ~/project/packages/std
          command: cargo clippy -- -D warnings
      - run:
          name: Clippy linting on vm (use flags for Rust stable support)
          working_directory: ~/project/packages/vm
          command: cargo clippy --no-default-features --features default-cranelift
      - run:
          name: Clippy linting on hackatom
          working_directory: ~/project/contracts/hackatom
          command: cargo clippy -- -D warnings
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: cargocache-v2-clippy-rust:1.41.1-{{ checksum "Cargo.lock" }}
