[package]
name = "hackatom"
version = "0.3.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "s"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'unwind'
incremental = false
overflow-checks = true

[workspace]

[features]
default = [ "integration" ]
# this enables integration testing (takes longer)
# for quicker tests, cargo test --no-default-features
integration = [ ]
# for more explicit tests, cargo test --features=backtraces
backtraces = [ "cosmwasm/backtraces" ]

[dependencies]
cosmwasm = { path = "../..", version = "0.3.0" }
serde = { version = "1.0.60", default-features = false, features = ["derive"] }
snafu = { version = "0.5.0", default-features = false, features = ["rust_1_30"] }
# needed for wasm-pack build process
wasm-bindgen = "0.2"

[dev-dependencies]
cosmwasm-vm = { path = "../../lib/vm", version = "0.3.1" }
