[package]
name = "hackatom"
version = "0.1.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'unwind'
incremental = false
overflow-checks = true


[dependencies]
cosmwasm = { path = "../.." }
serde_json = { version = "1.0.39" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
failure = "0.1.5"

[dev-dependencies]
wasmer-runtime = "0.8.0"
wasmer-runtime-core = "0.8.0"
wasmer-clif-backend = "0.8.0"
