[package]
name = "cosmwasm-schema-derive"
version = "1.0.0"
author = "Tomasz Kurcz <tom@confio.gmbh>"
edition = "2021"
description = "Derive macros for cosmwasm-schema"
repository = "https://github.com/CosmWasm/cosmwasm/tree/main/packages/schema"
license = "Apache-2.0"

[dependencies]
proc-macro2 = "1"
quote = "1"
serde_derive_internals = { git = "https://github.com/uint/serde", branch = "expose_rename_rules" }
syn = { version = "1", features = ["full", "printing", "extra-traits"] }

[lib]
proc-macro = true
