[package]
name = "cosmwasm-derive"
version = "0.13.0"
authors = ["Simon Warta <webmaster128@users.noreply.github.com>"]
edition = "2018"
description = "Standard library for Wasm based smart contracts on Cosmos blockchains"
repository = "https://github.com/CosmWasm/cosmwasm/tree/master/packages/std"
license = "Apache-2.0"
readme = "README.md"

[lib]
proc-macro = true

[features]
default = []

[dependencies]
syn = { version = "1.0", features = ["full"] }

[dev-dependencies]
