[package]
name = "cosmwasm-crypto"
version = "0.13.2"
authors = ["Mauro Lacy <maurolacy@users.noreply.github.com>"]
edition = "2018"
description = "Crypto bindings for cosmwasm contracts"
repository = "https://github.com/CosmWasm/cosmwasm/tree/main/packages/crypto"
license = "Apache-2.0"

[features]
default = []
# backtraces provides much better context at runtime errors (in non-wasm code)
# at the cost of a bit of code size and performance.
# This feature requires Rust nightly because it depends on the unstable backtrace feature.
backtraces = []

[lib]
# See https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false

[dependencies]
k256 = { version = "0.7.2", features = ["ecdsa"] }
sha2 = "0.9.1"
thiserror = "1.0"

[dev-dependencies]
serde = { version = "1.0.103", default-features = false, features = ["derive", "alloc"] }
serde_json = "1.0"
base64 = "0.13.0"
hex = "0.4"
rand_core = { version = "0.5", features = ["getrandom"] }
elliptic-curve = "0.8.4"
